export enum ProjectStatus {
  DRAFT = 'draft',
  IN_PROGRESS = 'in_progress',
  BRIEF_COMPLETE = 'brief_complete',
  PLANNING_MATCHING = 'planning_matching',
  PLANNING_ASSIGNED = 'planning_assigned',
  PLANNING_IN_PROGRESS = 'planning_in_progress',
  PLANNING_REVIEW = 'planning_review',
  IMPLEMENTATION_READY = 'implementation_ready',
  MATCHING = 'matching',
  MATCHED = 'matched',
  SPEC_IN_PROGRESS = 'spec_in_progress',
  SPEC_UNDER_REVIEW = 'spec_under_review',
  SPEC_COMPLETE = 'spec_complete',
  SCOPED = 'scoped',
  ASSIGNED = 'assigned',
  ACTIVE = 'active',
  UNDER_REVIEW = 'under_review',
  COMPLETED = 'completed',
  CANCELLED = 'cancelled',
  DISPUTED = 'disputed',
}
